### ISSUE TITLE
suggestion to add floating-label-wrapper class to parent div

### ISSUE THREAD

**Issue by anoopsinghbayes** [sandorTuranszky/angular-directive-implementing-float-label-pattern#1]
we can add this code in link function 

   $element.parent().addClass('floating-label-wrapper');

so that we do not have to add this class in the html mark-up every time to the parent DIV

[working code](http://plnkr.co/edit/g5LiHVlngaJ9QO02TBZh?p=preview)

**Comment by sandorTuranszky** [comment]
You are right but there is a reason why I didn't do that. The "floating-label-wrapper" class sets a position: relative style to a wrapping div element. But this element already has a class in twitter bootstrap so one could add this style to "form-group" class. Thus we end up with having less css and less Js/jQuery manipulations. 
The "floating-label-wrapper" class is only to demonstrate that the wrapper element should have position: relative but it is up to a developer who is going to use this directive to decide depending on html layout.
